<div id="benefits" class="ui-tabs-panel ui-widget-content" style="position: relative;"><div id="cth" class="ui-tabs ui-widget ui-widget-content ui-corner-all"><ul id="ctl" class="ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all"><li class="ui-state-default"><a href="#cat_1"><div>Core</div></a></li><li class="ui-state-default"><a href="#cat_2"><div>General</div></a></li><li class="ui-state-default ui-tabs-selected ui-state-active"><a href="#cat_3"><div>Household</div></a></li><li class="ui-state-default"><a href="#cat_4"><div>Education</div></a></li><li class="ui-state-default"><a href="#cat_5"><div>Health</div></a></li><li class="ui-state-default"><a href="#cat_6"><div>Income &amp; Assistance</div></a></li><li class="ui-state-default"><a href="#cat_7"><div>Work Experience</div></a></li></ul>


<div id="cat_4" class="ui-tabs-panel ui-widget-content ui-corner-bottom" style=""><center class="ui-no-results">Based on your answers so far, there are no additional questions for you in this portion of the Benefit Finder. Please proceed to one of the other tabs of the Benefit Finder, located to the left, to see if you have additional questions to answer.<br>You can view your results at any time by clicking the <a href="./benefits/benefit-finder/results">View Benefit Results</a> tab.</center></div>

<div id="cat_5" class="ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide"></div><div id="cat_6" class="ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide"></div><div id="cat_7" class="ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide"></div></div></div><div id="results" class="ui-tabs-panel ui-widget-content ui-tabs-hide"></div>

<div id="mybenefits" class="ui-tabs-panel ui-widget-content ui-tabs-hide"></div>

<div id="bcid" class="ui-benefits-count" style=""><div class="ui-benefits-count-bg" id="bcid-inner"><a href="#results"><div class="ui-benefit-total">Benefits You May be Eligible For: <div id="bc-value">21</div></div></a><div id="bcth"><div class="ui-benefit-category"><a href="#results&amp;rc=CDA">Career Development Assistance</a><div>6</div></div><div class="ui-benefit-category"><a href="#results&amp;rc=CHI">Child Care/Child Support</a><div>1</div></div><div class="ui-benefit-category"><a href="#results&amp;rc=DIA">Disability Assistance</a><div>2</div></div><div class="ui-benefit-category"><a href="#results&amp;rc=EDU">Education/Training</a><div>1</div></div><div class="ui-benefit-category"><a href="#results&amp;rc=HEA">Healthcare</a><div>1</div></div><div class="ui-benefit-category"><a href="#results&amp;rc=INS">Insurance</a><div>6</div></div><div class="ui-benefit-category"><a href="#results&amp;rc=VAD">Veterans - Active Duty</a><div>21</div></div></div></div></div>